# fly.toml app configuration file generated for wax-client on 2025-04-30T12:47:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wax-client'
primary_region = 'ord'

[build]
dockerfile = "Dockerfile-production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpu = 1

[env]
SERVER_URL = 'https://wax-server.fly.dev'
WEBSOCKET_SERVER_URL = 'wss://wax-server.fly.dev:3333'
PANDOC_URL='https://wax-pandoc.fly.dev'
