version: '3'

services:
  client:
    image: wax/wax/client-preproduction:latest
    ports:
      - ${CLIENT_PORT}:8080
    environment:
      - SERVER_URL=${SERVER_URL}

  server:
    image: wax/wax/server-preproduction:latest
    entrypoint: ['sh', 'scripts/setupDevServer.sh']
    command: ['node', 'startServer.js']
    ports:
      - ${SERVER_PORT}:3000
      - ${WS_SERVER_PORT}:${WS_SERVER_PORT}
    environment:
      - NODE_ENV=production
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WS_SERVER_PORT=${WS_SERVER_PORT}
      - CLIENT_URL=${CLIENT_URL}
      - CHATGPT_URL=${CHATGPT_URL}
      - CHATGPT_KEY=${CHATGPT_KEY}
      - MAILER_SENDER=${MAILER_SENDER:-dev@example.com}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH:-password-reset}
