FROM postgres:14

RUN apt-get update && apt-get install -y \
    postgresql-14-pgvector \
    && rm -rf /var/lib/apt/lists/*

COPY ./scripts/init-pgboss.sql /docker-entrypoint-initdb.d/init-pgboss.sql