const BOOK_COMPONENT_ADDED = 'BOOK_COMPONENT_ADDED'
const BOOK_COMPONENT_DELETED = 'BOOK_COMPONENT_DELETED'
const BOOK_COMPONENT_WORKFLOW_UPDATED = 'BOOK_COMPONENT_WORKFLOW_UPDATED'
const BOOK_COMPONENT_PAGINATION_UPDATED = 'BOOK_COMPONENT_PAGINATION_UPDATED'

const BOOK_COMPONENT_TRACK_CHANGES_UPDATED =
  'BOOK_COMPONENT_TRACK_CHANGES_UPDATED'

const BOOK_COMPONENT_TITLE_UPDATED = 'BOOK_COMPONENT_TITLE_UPDATED'
const BOOK_COMPONENT_CONTENT_UPDATED = 'BOOK_COMPONENT_CONTENT_UPDATED'
const BOOK_COMPONENT_UPLOADING_UPDATED = 'BOOK_COMPONENT_UPLOADING_UPDATED'
const BOOK_COMPONENT_LOCK_UPDATED = 'BOOK_COMPONENT_LOCK_UPDATED'
const BOOK_COMPONENTS_LOCK_UPDATED = 'BOOK_COMPONENTS_LOCK_UPDATED'
const BOOK_COMPONENT_TYPE_UPDATED = 'BOOK_COMPONENT_TYPE_UPDATED'
const BOOK_COMPONENT_TOC_UPDATED = 'BOOK_COMPONENT_TOC_UPDATED'
const BOOK_COMPONENT_UPDATED = 'BOOK_COMPONENT_UPDATED'
const YJS_CONTENT_UPDATED = 'YJS_CONTENT_UPDATED'

const STATUSES_TRANSLATION = {
  100: 'Unlocked by the admin of the system',
  101: 'Unlocked by the owner of the lock',
  102: 'Unlocked due to inactivity',
  103: 'Unlocked but found multiple locks',
  104: 'Unlocked by the system',
  105: 'Unlocked due to permission changes',
  200: 'LOCKED',
  300: 'Conversion error',
}

const STATUSES = {
  UNLOCKED_BY_ADMIN: 100,
  UNLOCKED_BY_OWNER: 101,
  UNLOCKED_DUE_INACTIVITY: 102,
  UNLOCKED_WITH_MULTIPLE_LOCKS: 103,
  UNLOCKED_BY_SYSTEM: 104,
  UNLOCKED_DUE_PERMISSIONS: 105,
  FINE: 200,
  CONVERSION_ERROR: 300,
}

module.exports = {
  BOOK_COMPONENT_ADDED,
  BOOK_COMPONENT_DELETED,
  BOOK_COMPONENT_WORKFLOW_UPDATED,
  BOOK_COMPONENT_UPDATED,
  BOOK_COMPONENT_PAGINATION_UPDATED,
  BOOK_COMPONENT_TRACK_CHANGES_UPDATED,
  BOOK_COMPONENT_TITLE_UPDATED,
  BOOK_COMPONENT_CONTENT_UPDATED,
  BOOK_COMPONENT_UPLOADING_UPDATED,
  BOOK_COMPONENT_LOCK_UPDATED,
  BOOK_COMPONENTS_LOCK_UPDATED,
  BOOK_COMPONENT_TYPE_UPDATED,
  BOOK_COMPONENT_TOC_UPDATED,
  STATUSES,
  STATUSES_TRANSLATION,
  YJS_CONTENT_UPDATED,
}
