#!/bin/sh

rm -f ./env.js
touch ./env.js

# remove double or single quotes around values, if any
SERVER_URL=${SERVER_URL#\"}
SERVER_URL=${SERVER_URL%\"}
SERVER_URL=${SERVER_URL#\'}
SERVER_URL=${SERVER_URL%\'}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\'}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\'}
CLIENT_PANDOC_URL=${CLIENT_PANDOC_URL#\"}
CLIENT_PANDOC_URL=${CLIENT_PANDOC_URL%\"}
CLIENT_PANDOC_URL=${CLIENT_PANDOC_URL#\'}
CLIENT_PANDOC_URL=${CLIENT_PANDOC_URL%\'}

cat <<EOF > ./env.js
window.env = {
    serverUrl: '${SERVER_URL}',
    websocketServerUrl: '${WEBSOCKET_SERVER_URL}',
    pandocUrl: '${CLIENT_PANDOC_URL}',
}
EOF

exec "$@"
