const BOOK_PRODUCTION_EDITORS_UPDATED = 'BOOK_PRODUCTION_EDITORS_UPDATED'
const TEAM_MEMBERS_UPDATED = 'TEAM_MEMBERS_UPDATED'
const TEAM_UPDATED = 'TEAM_UPDATED'

module.exports = {
  TEAM_MEMBERS_UPDATED,
  BOOK_PRODUCTION_EDITORS_UPDATED,
  TEAM_UPDATED,
}
