const TEMPLATE_CREATED = 'TEMPLATE_CREATED'
const TEMPLATE_UPDATED = 'TEMPLATE_UPDATED'
const TEMPLATE_DELETED = 'TEMPLATE_DELETED'

module.exports = { TEMPLATE_CREATED, TEMPLATE_UPDATED, TEMPLATE_DELETED }
