const EXPORT_PROFILE_UPDATED = 'EXPORT_PROFILE_UPDATED'
const EXPORT_PROFILE_CREATED = 'EXPORT_PROFILE_CREATED'
const EXPORT_PROFILE_DELETED = 'EXPORT_PROFILE_DELETED'

module.exports = {
  labels: {
    EXPORT_PROFILE_RESOLVER: '[EXPORT PROFILE RESOLVER] -',
  },
  subscriptions: {
    EXPORT_PROFILE_UPDATED,
    EXPORT_PROFILE_CREATED,
    EXPORT_PROFILE_DELETED,
  },
}
