export { default as DashboardPage } from './Dashboard.page'
export { default as ProducerPage } from './Producer.page'
export { default as LoginPage } from './Login.page'
export { default as RequestPasswordResetPage } from './RequestPasswordReset.page'
export { default as RequestVerificationEmailPage } from './RequestVerificationEmail.page'
export { default as UnverifiedUserPage } from './UnverifiedUser.page'
export { default as ResetPasswordPage } from './ResetPassword.page'
export { default as SignupPage } from './Signup.page'
export { default as CreateBook } from './CreateBook.page'
export { default as BookTitlePage } from './BookTitle.page'
export { default as ImportPage } from './Import.page'
export { default as VerifyEmailPage } from './VerifyEmail.page'
export { default as ExporterPage } from './Exporter.page'
// import AiPDFDesignerPage false
// console.log(AiPDFDesignerPage)
export { default as AiPDFDesignerPage } from './AiPDFDesigner.page'
export { default as AdminPage } from './Admin.page'
export { default as KnowledgeBasePage } from './KnowledgeBase.page'
export { default as TemplateMananger } from './TemplateManager.page'
