module.exports = {
  labels: {
    APPLICATION_PARAMETERS_CONTROLLER: '[APPLICATION PARAMETERS CONTROLLER] -',
    BOOK_CONTROLLER: '[BOOK CONTROLLER] -',
    BOOK_COLLECTION_CONTROLLER: '[BOOK COLLECTION CONTROLLER] -',
    BOOK_COMPONENT_CONTROLLER: '[BOOK COMPONENT CONTROLLER] -',
    CUSTOM_TAGS_CONTROLLER: '[CUSTOM TAGS CONTROLLER] -',
    DIVISION_CONTROLLER: '[DIVISION CONTROLLER] -',
    FILE_CONTROLLER: '[FILE CONTROLLER] -',
    MICROSERVICES_CONTROLLER: '[MICROSERVICES CONTROLLER] -',
    OBJECT_STORAGE_CONTROLLER: '[OBJECT STORAGE CONTROLLER] -',
    TEAM_CONTROLLER: '[TEAM CONTROLLER] -',
    TEMPLATE_CONTROLLER: '[TEMPLATE CONTROLLER] -',
    USER_CONTROLLER: '[USER CONTROLLER] -',
    EXPORT_PROFILE_CONTROLLER: '[EXPORT PROFILE CONTROLLER] -',
  },
  actions: {
    MESSAGE_CREATED: 'MESSAGE_CREATED',
    NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  },
}
