name: Deploy production

on: workflow_dispatch

jobs:
  deploy_server:
    name: Deploy production server
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: deploy
        run: |
          cd packages/server
          fly deploy -c fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_PRODUCTION_SERVER }}

  deploy_client:
    name: Deploy production client
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: deploy
        run: |
          cd packages/client
          fly deploy -c fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_PRODUCTION_CLIENT }}
