name: Deploy staging

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy_server:
    name: Deploy staging server

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/server
          fly deploy -c fly-staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_STAGING_SERVER }}

  deploy_client:
    name: Deploy staging client

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/client
          fly deploy -c fly-staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_STAGING_CLIENT }}
